use_frameworks!

platform :ios, '10.0'

target 'WOPLivenessDetect_Example' do
  pod 'WOPLivenessDetect', :path => '../'

  target 'WOPLivenessDetect_Tests' do
    inherit! :search_paths

    
  end
end
